name = "psyos-api"
main = "src/index.ts"
compatibility_date = "2026-03-25"
workers_dev = true

[vars]
APP_NAME = "psyos-api"
APP_VERSION = "0.1.0"
DEPLOY_ENVIRONMENT = "production"
DEPLOYED_VIA = "wrangler"
GIT_COMMIT = "unknown"
PUBLIC_API_URL = "https://api.psyos.org"
PUBLIC_WEB_URL = "https://psyos.org"

[[d1_databases]]
binding = "DB"
database_name = "psyos"
database_id = "01251378-444c-42b4-8ffa-9f7d7295c386"

[observability.logs]
enabled = true
