name = "psyos-api"
main = "src/index.ts"
compatibility_date = "2026-03-25"
workers_dev = true

[vars]
APP_NAME = "psyos-api"

[[d1_databases]]
binding = "DB"
database_name = "psyos"
database_id = "2608b749-ef3f-4ce0-9722-880863b61ac2"

[observability.logs]
enabled = true
